### ISSUE TITLE
PrcdaUihoCsvData is skipping the first line

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#116]
loadPrcdaData() and loadUihoData() are skipping the first line of the resource file.  These files don't contain a header line.  Either a header needs to be added or withSkipLines(1) needs to be changed/removed.

**Comment by depryf** [comment]
Simple change, I will take care of it.

I submitted another issue today (although that one will take a bit longer to be completed); once they are both ready, I will make a release.

**Comment by howew** [comment]
Thanks.

**Comment by depryf** [comment]
This is fixed. Will be released soon once that other issue is completed as well.
