### ISSUE TITLE
Update PRCDA and UIHO for 2020

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#119]
The new lookup tables for PRCDA and UIHO are attached.

The existing lookup tables do not have a header row.  These DO.  The code will need to be updated to start reading in from the 2nd row or the header row needs to be removed from these files.

The new UIHO lookup does not contain a UIHO facility column.  All existing references to UIHO facility should be removed from the library.  This will no longer be collected by CDC or updated moving forward.

[prcda-uiho2020.zip](https://github.com/imsweb/algorithms/files/6924540/prcda-uiho2020.zip)

**Comment by depryf** [comment]
This new algorithm will be available with version 3.6.
