### ISSUE TITLE
Implement Tract-Estimated Congressional Districts

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#121]
This is a new lookup for CDC and NAACCR.  It's a standard state, county at dx analysis, census tract 2010 lookup.

The NAACCR XML info for the algorithms API is as follows:
`<ItemDef naaccrId="tractEstCongressDist"
                naaccrNum="9405"
                naaccrName="Tract-Estimated Congressional District"
                length="2"
                recordTypes="A,M,C,I"
                parentXmlElement="Tumor"
                dataType="digits"/>`

I've attached the resource file.

The algorithm should implement the "flavors of unknown" (A, B, C, D) that are used by other algorithms in the library. 

[tract-estimated-congressional-districts.zip](https://github.com/imsweb/algorithms/files/6924731/tract-estimated-congressional-districts.zip)

**Comment by kirbykn** [comment]
Are there descriptions for the possible tractEstCongressDist values that I can put in the comment for 'computeTractEstCongressDist'?

**Comment by howew** [comment]
Yes, I'll email them to you.

**Comment by depryf** [comment]
This new algorithm will be available with version 3.6.
