### ISSUE TITLE
Implement Cancer Reporting Zones

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#122]
Another state, county at dx analysis, census tract lookup.

This is only being collected by 12 states.

The NAACCR XML information for the algorithms API implementation is as follows:
`<ItemDef naaccrId="cancerReportingZone"
                naaccrNum="9415"
                naaccrName="Cancer Reporting Zone"
                length="8"
                recordTypes="A,M,C,I"
                parentXmlElement="Tumor"/>`

I've attached the resource file.

The algorithm should implement the "flavors of unknown" (A, B, C, D) that are used by other algorithms in the library.

[cancer-reporting-zones.zip](https://github.com/imsweb/algorithms/files/6924751/cancer-reporting-zones.zip)

**Comment by kirbykn** [comment]
Should the list of valid states only include the 12 states that are collecting this value?

**Comment by howew** [comment]
Lets keep the valid state part similar to the other algorithms.  For the states other than the main 12 it will just come back as whatever letter equates to "not found in the lookup table".

**Comment by depryf** [comment]
This new algorithm will be available with version 3.6.
