### ISSUE TITLE
Add support for Lymphoid Neoplasm Recode 2021

### ISSUE THREAD

**Issue by depryf** [imsweb/algorithms#129]
This is on hold pending internal discussion about the timing.

https://seer.cancer.gov/lymphomarecode/lymphoma-2021.html

**Comment by depryf** [comment]
Just add the latest one.

**Comment by flynngr** [comment]
Same comment as with the AYA one, regarding adding a new algorithm. 

Do you want to code from the website or use my lookup? I tend to think it's better to code independently in case there is an error in mine.

**Comment by depryf** [comment]
I will use the website information. 

Unlike AYA, this algorithm doesn't exist yet. So there is no question of replacing vs duplicating and I will just add the latest version.

**Comment by depryf** [comment]
Algorithm ID: seer-lymphoid-neoplasm-recode
Algorithm name: SEER Lymphoid Neoplasm Recode
Algorithm version: 2021 Revision
Algorithm info: SEER Lymphoid Neoplasm Recode
Algorithm URL: https://seer.cancer.gov/lymphomarecode/lymphoma-2021.html

Input: standard site and histology
Output: non-standard field (seerLymphoidNeoplasmRecode)

**Comment by depryf** [comment]
There will probably be other versions of this algorithm supported in the future, let's add the version to the output field name:

seerLymphoidNeoplasmRecode2021

@flynngr this name seems  a bit long; it is still under the max limit in NAACCR XML, which is 32 characters, and so I don't have an issue keeping it as-is.

But if are not against it, maybe we could abbreviate some of the words?

**Comment by flynngr** [comment]
I'm not against changing it, but it doesn't bother me either.

**Comment by depryf** [comment]
This has been completed, it will be available in the next release.
