### ISSUE TITLE
New brain/cns recode

### ISSUE THREAD

**Issue by flynngr** [imsweb/algorithms#130]
Can we add this? https://seer.cancer.gov/seerstat/variables/seer/brain_cns-recode/

**Comment by depryf** [comment]
The format is similar to other SEER algorithms we already support but unfortunately, that page contains things like "none of the above codes" for histology and that is going to complicate translating that table into our normalized format. It's very doable, it will just take more efforts.

Algorithm ID: seer-brain-cns-recode
Algorithm name: SEER Brain/CNS Recode
Algorithm version: 2016 WHO
Algorithm info: SEER Brain/CNS Recode based on the 2016 World Health Organization Classification of Tumors of the Central Nervous System (CNS)
Algorithm URL: https://seer.cancer.gov/seerstat/variables/seer/brain_cns-recode/

Input: standard site, histology and behavior
Output: non-standard field (seerBrainCnsRecode)

**Comment by depryf** [comment]
@flynngr I have a question about this one: most other algorithms have a "default" value that is usually all 9's. 

This one re-codes "all other combination" with an actual code of 27.

Should 27 be considered the unknown value. For example, if one of the input is missing (making it impossible to evaluate the result), is it OK for the algorithm to return 27? 

That's consistent with how the other algorithms work, except it feels weird to use a code like 27 for that...

**Comment by flynngr** [comment]
We didn’t put it in the documentation because SEER doesn’t have any, but an error or missing/invalid input would be 99 in my code.

Since this recode is only brain/cns, it makes sense for ‘other’ to be separate from invalid/error, whereas some of the other site recodes are supposed to handle all cases.

**Comment by flynngr** [comment]
Just curious why 2016?

**Comment by depryf** [comment]
From the link you gave me:

A new Brain/CNS Recode, based on the 2016 World Health Organization Classification of Tumors of the Central Nervous System

Most algorithm are defined in a specific year and somehow reference that year in their version, and I assume it must be really rare for an algorithm to release more than one version in any given year, so I think it's a good candidate for a suffix. But at the end, we can use whatever we want.

**Comment by depryf** [comment]
@flynngr the SEER website documentation for this algorithm says that the data is based on the "2016 WHO classifications..." and so I thought the version of this algorithm (and the variable suffix) would be 2016.

But when I downloaded the Excel data file from that page, the filename contained "2020Revision".

Should the version of this algorithm be "2016 WHO" or "2020 Revision"?

**Comment by depryf** [comment]
I used "2020" as the algorithm version (and variable name), that made more sense to me than using 2016. We can revisit if needed.
