### ISSUE TITLE
Rare cancers recode

### ISSUE THREAD

**Issue by flynngr** [imsweb/algorithms#131]
https://seer.cancer.gov/seerstat/variables/seer/raresiterecode/

We have released this field in the public data, but there have recently been questions about the coding and the NCI is reviewing it again. I think we should hold off coding this in algorithms for now, but I wanted to create a space holder.

**Comment by depryf** [comment]
@flynngr this is 2 years old. I don't really mind the issue, but I am wondering if we should close it for now and re-open it when a decision has been made. I don't love having an issue that just can't be worked on and closed.

**Comment by depryf** [comment]
This issue is 3 years old. I am closing it. We can re-open one when we are ready to actually do this.
