### ISSUE TITLE
Add new algorithm for SEER Site Recode 2023

### ISSUE THREAD

**Issue by depryf** [imsweb/algorithms#170]
Notifying @howew  and @flynngr 

https://seer.cancer.gov/siterecode/icdo3_2023/
https://seer.cancer.gov/siterecode/icdo3_2023_expanded/

Algorithm ID = seer-site-recode-2023
Algorithm Name = SEER Site Recode ICD-O-3
Algorithm Version = 2023 Revision

Input variables:
- primary site
- histology ICD-O-3
- behavior ICD-O-3

Output variables:

name = SEER Site Recode ICD-O-3 2023 Revision
id = seerSiteRecode2023
number = 9412
length = 3
type = digit

name = SEER Site Recode ICD-O-3 2023 Revision Expanded
id = seerSiteRecode2023Expanded
number = 9413
length = 3
type = digit

There is no "unknown" value (other than blank), and from what I see the algorithm can compute blank values (there isn't a catch-all condition at the end).

**Comment by howew** [comment]
Should we create one?  What does the 2008 WHO version do?

**Comment by depryf** [comment]
No, I don't think we should (or that we can).

The 2008 version has an explicit catch-everything-else mapping at the end of their table (for code 99999)

https://seer.cancer.gov/siterecode/icdo3_dwhoheme/index.html

These new tables just don't have that.

If you want to petition SEER to change the tables, feel free. But I am staying out of it :-)
