### ISSUE TITLE
Update to Derived Grade 2018

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#179]
The derived grade 2018 algorithm should be updated to add specific logic for Hematopoietic and Lymphoid Neoplasms.

Schemas covered by this include:
•	00790	Lymphoma
•	00795	Lymphoma-CLL/SLL
•	00811	Mycosis Fungoides
•	00812	Primary Cutaneous Lymphomas (excluding Mycosis Fungoides)
•	00821	Plasma Cell Myeloma
•	00822	Plasma Cell Disorders
•	00830	HemeRetic

The priority order, from BEST to WORST, is:
•	8, blank

The original issue for this algorithm can be found here: https://github.com/imsweb/algorithms/issues/160

The documentation in that issue was missing this part of the logic.

**Comment by depryf** [comment]
So the current logic is this:

if schema ID is 00480 (breast) and behavior is 2, use "H, M, L, 3, 2, 1, D, C, B, A, 9, blank"
if schema ID is 00480 (breast) and behavior is 3, use "3, 2, 1, H, M, L, D, C, B, A, 9, blank"
if schema ID is not 00480 (breast), use "S, 5, 4, 3, 2, 1, E, D, C, B, A, H, M, L, 9, blank"

Does it need to become this:

if schema ID is 00480 (breast) and behavior is 2, use "H, M, L, 3, 2, 1, D, C, B, A, 9, blank"
if schema ID is 00480 (breast) and behavior is 3, use "3, 2, 1, H, M, L, D, C, B, A, 9, blank"
if schema ID is 00790, 00795 (etc...), use "8, blank"
if schema ID is not 00480 (breast) and not 00790, 00795, etc..., use "S, 5, 4, 3, 2, 1, E, D, C, B, A, H, M, L, 9, blank"

Does that look correct?

Is this needed for this upcoming February SEER submission?

**Comment by howew** [comment]
Yes, that looks right.  I don't know if its needed for February or not, to be honest.

**Comment by schusslern** [comment]
yes, this looks good Fabian

**Comment by depryf** [comment]
These changes are done. Since this is not needed for this upcoming SEER submission, I am not going to force a release right away. There is another issue for updating the site-specific surgery lookups, I will wait for that one to be completed as well...
