### ISSUE TITLE
Add 2024 site-specific surgery codes

### ISSUE THREAD

**Issue by jlorentson** [imsweb/algorithms#180]
New "B-codes" are being added in the NAACCR 2024 update for these surgery sites: Thyroid, Pancreas, Lung, Breast, Colon.

**Comment by depryf** [comment]
Notifying @schusslern 

So @jlorentson are you just going to copy the current data for those and add a "B" prefix?  Or are the changes a bit more complicated than that?

**Comment by schusslern** [comment]
what do you mean copy the current data?  the 2023 and prior data does not change.   the 2024 data will have a new set of codes

**Comment by jlorentson** [comment]
In the associated squish issue, there is a spreadsheet with the new codes for the relevant sites. I am copying the 2023 codes to a new file (`site-specific-surgery-tables-2024.xml`), updating the relevant sites based on the spreadsheet, and leaving the rest as they were last year.

**Comment by jlorentson** [comment]
I.e. yes, it is a bit more complicated, but I have something to work from (the spreadsheet).

**Comment by depryf** [comment]
OK, thanks. I just wanted to know what to expect.
