### ISSUE TITLE
Revised EPHT tables

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#188]
NPCR has provided a new set of lookup tables for the EPHT sub county fields, which I've attached.  They've asked to replace the existing tables with the new tables rather than trying to figure out what has changed.

[Subcounty_Crosswalk_25JUL23.csv](https://github.com/user-attachments/files/16059052/Subcounty_Crosswalk_25JUL23.csv)

**Comment by depryf** [comment]
That data file is not needed; we don't maintain that data in this project anymore.

The data now comes from the SEER data file:

https://seer.cancer.gov/seerstat/variables/countyattribs/ctattrdict.html

We will need that data file to be updated/released on the SEER website before this issue can be resolved.

**Comment by depryf** [comment]
I updated the SEER data in the project; I *think* the updated data contains the latest EPHT table. 

I don't think there is anything to do for this issue...
