### ISSUE TITLE
Persistent Poverty

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#189]
NAACCR and NPCR would like to add a persistent poverty field.  This field is already in the large file containing tract attributes.  We just need to add an algorithm to retrieve it.  The tentative xml definition, including naaccrId and naaccrNum, is below.

        <ItemDef naaccrId="persistentPoverty"
            naaccrNum="9625"
            naaccrName="Persistent Poverty"
            length="1"
            recordTypes="A,M,C,I"
            parentXmlElement="Tumor"/>

**Comment by depryf** [comment]
@howew I have a few questions.

1. Is there an unknown value defined for this algorithm (I don't think there is)?
2. Is this own by NPCR or NAACCR (I think it's NPCR)?
3. Is the name "NPCR Persistent Poverty" OK?
4. Is the version "v1 released in August 2024" OK?
5. Many other census-based algorithms use A, B, C and D as flavors of unknown; do you want this algorithms to do that as well?

**Comment by howew** [comment]
I will follow up with NPCR and NAACCR and let you know.

**Comment by depryf** [comment]
Answers:

1. No default.
2. It's owned by USDA, so neither prefix will be used.
3. Use "Persistent Poverty".
4. Use "v1 released by USDA on 12/08/2023"
5. Yes, use those unknown flavors.

In addition, reference this URL:

https://www.ers.usda.gov/data-products/poverty-area-measures/
