### ISSUE TITLE
2023 Site recodes

### ISSUE THREAD

**Issue by flynngr** [imsweb/algorithms#195]
I am currently switching my Recodes code to use the Algorithm versions of the regualar and extended 2023 site recode fields.

In testing the change, I found at least one discrepancy. See attached. File # 1 was created from Algorithms, but I think the values in file # 2 are correct. I included the input fields in the comparison. 

As a reminder, here are the docs for these:
- https://seer.cancer.gov/siterecode/icdo3_2023/
- https://seer.cancer.gov/siterecode/icdo3_2023_expanded/

[comparison-results-20241012_133623.txt](https://github.com/user-attachments/files/17721549/comparison-results-20241012_133623.txt)

**Comment by flynngr** [comment]
I did a full comparison using the entire SEER November 2023 submission, and there were 60 total discrepancies. All were behavior 0/1 cases that should be coded to 81 in non-expanded and 84 in expanded.

Let me know if you need more information.

For SEER and NAACCR, a fix is not urgent, but this change may need to be pushed fast for NPCR if they are asking for it.

**Comment by depryf** [comment]
This has been fixed and version 4.12 is now available on Maven Central.
