### ISSUE TITLE
ICCC Major Category

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#54]
I would like to request that the calculation for the ICCC Major Category be added to the library.  The ICCC Major Category collapses the 3-digit ICCC code to 2 digits, each 2 digit code represents a different major site category.

I've attached some code, it may or may not compile but it should be more than sufficient to get folks started.

[iccc-major-category.txt](https://github.com/imsweb/algorithms/files/3228522/iccc-major-category.txt)

**Comment by depryf** [comment]
@howew would it be OK to add this as a second output of the ICCC algorithm? Right now the algorithm returns "iccc", it would also return "icccMajorCategory"? 

The downside is that in your application, there won't be a way to have one without the other. I don't know if it's a deal breaker for you.

If we can't do that, then there will be an algorithm dependency; your application will need to make sure to run the ICCC one first before it can run the IcccMajorCategory...

**Comment by depryf** [comment]
@garybeverungen can you please implement this new algorithm? You will need to add a new package/utility class, but also register a new "Algorithm" in the new framework (see Algorithms). Thanks.

**Comment by howew** [comment]
@depryf Isn't that similar to the way the survival calculations work?  I'm fine with that.

**Comment by depryf** [comment]
Yup, it's similar to that. Like I said, from your perspective, it means a user won't be able to add just the ICCC, your application will add both ICCC and ICCC Major Category together. I don't think it's an issue though, and so let's go with that for now. That will make this issue much simpler.

**Comment by depryf** [comment]
The changes have been merged, they will be available with version 2.1.

**Comment by depryf** [comment]
@howew the ICCC algorithm support two version (Third Edition and WHO); we are in the process of adding a third version (Third Edition/IARC 2017).

You provided the logic to compute the "ICCC major category". Does that logic apply to any version, or is it tied to one of those versions? It takes the "ICCC recode" value as an input, but that value is version-dependent. So it's not clear to me if the major category is supposed to work for all versions (including the new one we are adding) or if its tied to a specific version.

**Comment by howew** [comment]
The logic should apply to any version.  I quickly compared the "main classification" columns in the following tables and I didn't spot any new main classifications.  If there are new ones you can just update the ranges.

https://seer.cancer.gov/iccc/iccc-who2008.html
https://seer.cancer.gov/iccc/iccc-iarc-2017.html

**Comment by depryf** [comment]
Great, thanks!
