### ISSUE TITLE
Record Number Recode output by the Survival Time Alorithm

### ISSUE THREAD

**Issue by flynngr** [imsweb/algorithms#56]
[record.number.recode.error.algorithms.xlsx](https://github.com/imsweb/algorithms/files/3262520/record.number.recode.error.algorithms.xlsx)
I attached 3 patients where the record number recede comes out wrong.   I found more cases than these, but the only ones I saw were when the last two records were after the study cutoff.

Col C is what we want the output to be.  Col D is the current output.  Cols E-I are the algorithms inputs, J-P are the rest of the outputs (these are correct).

Let me know if you need more information.

**Comment by depryf** [comment]
@bekeles I think you worked on that algorithm a while ago. Do you mind taking a look. Make sure to work on a branch and to beef up the unit tests. Thanks.

**Comment by flynngr** [comment]
Sorry, I left out the exact statement of the issue.  For these 3 patients, we would want the sort order to match the order of their diagnosis dates (not sequence number).

**Comment by bekeles** [comment]
The algorithm don't calculate anything for the record if diagnosis year is invalid or after the cutoff year. All the records on the spreadsheet have a diagnosis date after the cut of date (12/31/2016). Do we want to change that? That means do we want to set the record number recode even though all the survival results are 9 filled?

**Comment by flynngr** [comment]
Yes.  It was already calculating a record number recode for those cases, but it is ordered incorrectly.  We want to keep everything else the same for cases after the study cutoff – the LC dates are filled, survival months and flags are 9s and the DX date is blank.

**Comment by depryf** [comment]
@flynngr the changes have been merged into master. Are you expecting them to be released soon? Do you need them now?

**Comment by flynngr** [comment]
It’s not ‘urgent,’ but I could use them anytime.  This is the field that SEER*Prep expects sorting by, so it’s part of the system I’m developing/testing right now.
