### ISSUE TITLE
Algorithms.java - override getUnknownValues() in createIarc() function

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#66]
Can an override for getUnknownValues() be added to the createIarc() method in Algorithms.java?

The IARC functions return an unknown value (literal string "null").

Therefore, I would like "null" to be included in the list when calling getUnknownValues().... either that, or change the IARC algorithms to return null instead of "null".

**Comment by howew** [comment]
I believe the issue may lie with the Objects.toString method on/about line 1360 in Algorithms.java - for example....

                    outputTumor.put(FIELD_IARC_MP_INDICATOR, Objects.toString(dto.getInternationalPrimaryIndicator(), null));
                    outputTumor.put(FIELD_IARC_MP_SITE_GROUP, dto.getSiteGroup());
                    outputTumor.put(FIELD_IARC_MP_HIST_GROUP, Objects.toString(dto.getHistGroup(), null));
                    outputTumor.put(FIELD_IARC_MP_HISTOLOGY, dto.getHistology());

**Comment by depryf** [comment]
No algorithms should return the string "null". That's a bug that needs to be fixed in that algorithm. I will take a look at the code you referenced when I can.

**Comment by howew** [comment]
Can you look at this before you do the next release?

**Comment by depryf** [comment]
I can't reproduce this issue within the library. 

Those calls to Objects.toString() are there to avoid returning the string "null" (that second parameter is the default value if the first param is null, and so by passing null, we ensure that the value null remains null and anything else becomes a string).

Do you still see this happening, and if you do, is there anyway you could provide the inputs that create that situation?

**Comment by howew** [comment]
Primary site: "C569"
Histology: "8441"
Behavior: "3"
Date of DX: "200002"  (no day)
Sequence Number: "03"

The tumor record in the algorithm output contains these values after running the algorithm with those inputs:

iarcMpHistologicTypeIcdO3: "8441"
iarcMpIndicator: "1"
iarcMpHistGroup: null
iarcMpSiteGroup: null

**Comment by depryf** [comment]
And what is the problem with that output?

The indicator is set to the String "1", the histology is set to the String "8441" and the two groups are set to a null reference (not the String "null", but a null object).

You originally reported that the algorithm returns the String "null" for some input. But that doesn't seem to be the case with that example.

**Comment by howew** [comment]
I misspoke, but as far as I can tell, it is the only algorithm in the entire library that can return null.  The rest return missing/blank or a special code when they cannot be calculated.

**Comment by depryf** [comment]
OK, this isn't really about the bug originally describe then.

It seems logical to considered a null value as being unknown; I thought it was something we agreed upon when we first talked about the framework and its support for unknown values. A null value is never going to be "known", and so why adding it explicitly to all individual algorithms that might return it?

If this is difficult for you, or if you don't agree with that, I can add the value null to the unknown list for this specific algorithm. I just thought it would be easier for you to always consider null as unknown...

**Comment by howew** [comment]
I'll make the change on my end.
