### ISSUE TITLE
Census Tract Poverty Indicator data for 2012-2016

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#72]
In the process of updating the SAS program for census tract poverty I discovered that the 2012-2016 data was not being coded correctly.  This would affect cases diagnosed in 2014.

The resource file for the 2012-2016 data needs to be updated.  Many of the tracts that were coded as 1 should have been coded as something else.

I have the file ready.  I just need to create a branch and commit.

**Comment by depryf** [comment]
Fixed, and merged. Will be available with version 2.5.
