### ISSUE TITLE
Record Number Recode in Survival is missing its leading zero

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#76]
There is an issue with item #1775 (record number recode), which is part of the survival algorithm.  

This data item should be padded on the left with a zero.

This is per the NAACCR specifications, which can be found here:

http://datadictionary.naaccr.org/default.aspx?c=10#1775​

Can the leading zero be added to the output for this field?

**Comment by depryf** [comment]
Yes, that can be done, it's simple enough.

**Comment by howew** [comment]
Thanks.  I'm still waiting for the seer cause of death SAS program to be updated.  Might want to hold off on any release until I've had a chance to test that.


________________________________

**Comment by depryf** [comment]
Done.
