### ISSUE TITLE
List of input fields for county at dx analysis

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#81]
The list of input fields for the county of dx analysis algorithm in Algorithms.java includes a few extra fields that are not actually used by the algorithm.

These include:
State at dx geocode 70/80/90
State at dx geocode 2000
State at dx geocode 2010
State at dx geocode 2020

There are setters and getters for these in CountyAtDxAnalysisInputDto.java, and presumably that's why they were included among the input fields, but the getters are never actually used.  It might be best to remove them to avoid confusion.  The algorithm never uses state at dx geocode.  The SAS code also never uses it.

Incidentally, the county at dx geocode 2020 and census tract certainty 2020 fields are also never used, but I can see them being used eventually... so I'll leave it up to you to decide if you want to keep them, comment them out, or whatever.

No rush on this whatsoever, btw.

**Comment by depryf** [comment]
This is fixed, I removed the properties from the input object.
