### ISSUE TITLE
Incorrect input value being set for countyAtDxAnalysis in Algorithms.java

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#83]
On line 1454 the following:

inputDto.setCountyAtDxGeocode2000((String)inputTumor.get(FIELD_COUNTY_AT_DX_GEOCODE_2010));

Should be

inputDto.setCountyAtDxGeocode**2010**((String)inputTumor.get(FIELD_COUNTY_AT_DX_GEOCODE_2010));

**Comment by depryf** [comment]
This is fixed (unreleased).
