### ISSUE TITLE
Change to SEER Cause Specific Death Clasification Algorithm

### ISSUE THREAD

**Issue by flynngr** [imsweb/algorithms#88]
We need to add some codes to all 3 "sequence number 1" lookup tables for anal caners only.

ICD-8/Sequence 1 table: replace 153.6 with 152-155 for anal cancers
ICD-9/Sequence 1 table:  add 152-155 for anal cancers
ICD-10/Sequence 1 table:  add:  C17-C21 for anal cancers

**Comment by depryf** [comment]
This will be released with version 2.13.
