### ISSUE TITLE
Add Adolescent / Young Adult (AYA) Site recode

### ISSUE THREAD

**Issue by isaackcr** [imsweb/algorithms#90]
Please add AYA site recode to the algorithms Java library:
https://seer.cancer.gov/ayarecode/aya-who2008.html

**Comment by depryf** [comment]
@isaackcr it looks like this fell of my list, sorry about that. I will find the time to do this soon.

**Comment by isaackcr** [comment]
No problem, we already implemented it internally so no rush.

**Comment by depryf** [comment]
This work is completed. I am not going to force a release for this; it will go out when version 2.16 gets released.
