### ISSUE TITLE
Changes to the SEER Cause of death classification

### ISSUE THREAD

**Issue by depryf** [imsweb/algorithms#92]
SEER is now calculating these fields for sequence #s 0-59 rather than only sequence #s 0-1.

The changes will be reflected here (as of now, the page has not been updated yet):
https://seer.cancer.gov/causespecific/

**Comment by flynngr** [comment]
Specifically, records with sequence numbers 2-59 (previously coded to N/A) need to be coded according to the same algorithm as tumors with sequence number 1.

**Comment by depryf** [comment]
@flynngr  could you please take a look at my changes: https://github.com/imsweb/algorithms/commit/499be61123cada73b2cfdba4c00864c4134a7cf2

Thanks!

**Comment by flynngr** [comment]
I think that you still need to either update the lookup table to include seq# 1-59 instead of just 1 OR group them into a “1” before consulting the lookup table (line 256).

**Comment by depryf** [comment]
@flynngr thanks for pointing that out. I didn't even realize the code was calling a lookup at the end!

I changed the lookup to say "1-59" instead of "1" and I change the call to it to translate any sequence between 1 and 59 to the string "1-59".

Does everything look alright now?

**Comment by flynngr** [comment]
I think that this looks good.  Do you want me run some data through to test against my previously ‘corrected’ results?

**Comment by depryf** [comment]
That would be great! I released a snapshot, you can reference it by changing the version to 2.14-SNAPSHOT.

**Comment by flynngr** [comment]
I have tested this and it looks good.

**Comment by depryf** [comment]
Awesome, thanks.

I will close this issue. This will be released when something else comes up, or I can make a release of someone needs it earlier...
