### ISSUE TITLE
Change to Historic Stage Algorithm

### ISSUE THREAD

**Issue by flynngr** [imsweb/algorithms#93]
Lynn Ries pointed out an error with the treatment of one of the CS Lymph Nodes values for Pancreas Head and Neck.  Code 110 was coded as distant and it should be regional.

**Comment by depryf** [comment]
@flynngr the changes are merged. Do you need a release right away because of this?

**Comment by flynngr** [comment]
There is absolutely no rush to release publicly,  but it would be good if I can access vis a snapshot.


-------- Original message --------
