### ISSUE TITLE
NHIA inconsistent with Hispanic Origin (#190)

### ISSUE THREAD

**Issue by howew** [imsweb/algorithms#97]
If the birthplace is a predominantly non-Hispanic country the NHIA value is being set to non-Hispanic even if the Hispanic Origin (190) field is set to a Hispanic value (except 6, which is currently working fine because of the way its coded).

Lines 350 and 351 in NhiaUtils.java need to be removed.
Line 352 in NhiaUtils.java needs to be changed to an 'if' instead of an 'else if'.

**Comment by depryf** [comment]
This was fixed, will be available with version 2.15.
